package com.cricket.scorecard.service;

import com.cricket.scorecard.dto.BatsmanCardDTO;
import com.cricket.scorecard.dto.BowlerCardDTO;
import com.cricket.scorecard.dto.ScorecardResponse;
import com.cricket.scorecard.model.Innings;
import com.cricket.scorecard.model.Match;
import com.cricket.scorecard.repository.*;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

@Service
public class PdfService {

    private final MatchRepository matchRepository;
    private final ScoringService scoringService;

    public PdfService(MatchRepository matchRepository, ScoringService scoringService) {
        this.matchRepository = matchRepository;
        this.scoringService = scoringService;
    }

    public byte[] generateMatchReport(String matchKey) throws IOException {
        Match match = matchRepository.findByMatchKey(matchKey)
                .orElseThrow(() -> new RuntimeException("Match not found"));

        if (!"COMPLETED".equals(match.getStatus())) {
            throw new RuntimeException("PDF only available for completed matches");
        }

        ScorecardResponse scorecard = scoringService.buildScorecard(matchKey);

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(baos);
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf);

        PdfFont bold = PdfFontFactory.createFont(com.itextpdf.io.font.constants.StandardFonts.HELVETICA_BOLD);
        PdfFont normal = PdfFontFactory.createFont(com.itextpdf.io.font.constants.StandardFonts.HELVETICA);

        // HEADER
        Paragraph header = new Paragraph(match.getTeam1Name() + " vs " + match.getTeam2Name())
                .setFont(bold).setFontSize(20)
                .setTextAlignment(TextAlignment.CENTER)
                .setFontColor(new DeviceRgb(30, 30, 60));
        document.add(header);

        String subHeader = (match.getVenue() != null ? match.getVenue() : "") +
                (match.getMatchDate() != null ? " | " + match.getMatchDate() : "");
        if (!subHeader.isBlank()) {
            document.add(new Paragraph(subHeader).setFont(normal).setFontSize(11)
                    .setTextAlignment(TextAlignment.CENTER));
        }

        // RESULT
        if (match.getResult() != null) {
            document.add(new Paragraph("Result: " + match.getResult())
                    .setFont(bold).setFontSize(13)
                    .setFontColor(new DeviceRgb(0, 100, 0))
                    .setTextAlignment(TextAlignment.CENTER));
        }

        document.add(new Paragraph("\n"));

        // INNINGS 1
        if (scorecard.getInnings1() != null) {
            addInningsSection(document, bold, normal, "Innings 1", scorecard.getInnings1());
        }

        document.add(new Paragraph("\n"));

        // INNINGS 2
        if (scorecard.getInnings2() != null) {
            addInningsSection(document, bold, normal, "Innings 2", scorecard.getInnings2());
        }

        // FOOTER
        document.add(new Paragraph("\nGenerated by Cricket Scorecard App | Match Key: " + matchKey)
                .setFont(normal).setFontSize(9)
                .setTextAlignment(TextAlignment.CENTER)
                .setFontColor(new DeviceRgb(100, 100, 100)));

        document.close();
        return baos.toByteArray();
    }

    private void addInningsSection(Document doc, PdfFont bold, PdfFont normal,
                                    String title, ScorecardResponse.InningsData innings) throws IOException {

        doc.add(new Paragraph(title + ": " + innings.getBattingTeam() + " " +
                innings.getTotalRuns() + "/" + innings.getTotalWickets() +
                " (" + innings.getLegalBallsBowled() / 6 + "." + innings.getLegalBallsBowled() % 6 + " Ov)")
                .setFont(bold).setFontSize(14).setFontColor(new DeviceRgb(30, 30, 90)));

        // BATTING TABLE
        doc.add(new Paragraph("Batting").setFont(bold).setFontSize(12));

        Table battingTable = new Table(UnitValue.createPercentArray(new float[]{30, 25, 5, 5, 5, 5, 10}))
                .useAllAvailableWidth();

        addHeaderRow(battingTable, bold, new String[]{"Batsman", "How Out", "R", "B", "4s", "6s", "SR"});

        if (innings.getBatting() != null) {
            for (BatsmanCardDTO b : innings.getBatting()) {
                battingTable.addCell(new Cell().add(new Paragraph(b.getName()).setFont(normal).setFontSize(9)));
                battingTable.addCell(new Cell().add(new Paragraph(b.getDismissalInfo() != null ? b.getDismissalInfo() : "not out").setFont(normal).setFontSize(9)));
                battingTable.addCell(new Cell().add(new Paragraph(String.valueOf(b.getRuns())).setFont(normal).setFontSize(9)));
                battingTable.addCell(new Cell().add(new Paragraph(String.valueOf(b.getBalls())).setFont(normal).setFontSize(9)));
                battingTable.addCell(new Cell().add(new Paragraph(String.valueOf(b.getFours())).setFont(normal).setFontSize(9)));
                battingTable.addCell(new Cell().add(new Paragraph(String.valueOf(b.getSixes())).setFont(normal).setFontSize(9)));
                battingTable.addCell(new Cell().add(new Paragraph(String.valueOf(b.getStrikeRate())).setFont(normal).setFontSize(9)));
            }
        }

        // Extras row
        battingTable.addCell(new Cell(1, 3).add(new Paragraph("Extras").setFont(bold).setFontSize(9)));
        battingTable.addCell(new Cell().add(new Paragraph("W:" + innings.getWides() + " Nb:" + innings.getNoBalls() + " B:" + innings.getByes() + " Lb:" + innings.getLegByes()).setFont(normal).setFontSize(9)));
        battingTable.addCell(new Cell(1, 3).add(new Paragraph(String.valueOf(innings.getExtrasTotal())).setFont(normal).setFontSize(9)));

        doc.add(battingTable);
        doc.add(new Paragraph("\n"));

        // BOWLING TABLE
        doc.add(new Paragraph("Bowling").setFont(bold).setFontSize(12));
        Table bowlingTable = new Table(UnitValue.createPercentArray(new float[]{30, 8, 8, 8, 8, 10}))
                .useAllAvailableWidth();

        addHeaderRow(bowlingTable, bold, new String[]{"Bowler", "O", "M", "R", "W", "Econ"});

        if (innings.getBowling() != null) {
            for (BowlerCardDTO b : innings.getBowling()) {
                bowlingTable.addCell(new Cell().add(new Paragraph(b.getName()).setFont(normal).setFontSize(9)));
                bowlingTable.addCell(new Cell().add(new Paragraph(b.getOversDisplay()).setFont(normal).setFontSize(9)));
                bowlingTable.addCell(new Cell().add(new Paragraph(String.valueOf(b.getMaidens())).setFont(normal).setFontSize(9)));
                bowlingTable.addCell(new Cell().add(new Paragraph(String.valueOf(b.getRunsConceded())).setFont(normal).setFontSize(9)));
                bowlingTable.addCell(new Cell().add(new Paragraph(String.valueOf(b.getWickets())).setFont(normal).setFontSize(9)));
                bowlingTable.addCell(new Cell().add(new Paragraph(String.valueOf(b.getEconomy())).setFont(normal).setFontSize(9)));
            }
        }

        doc.add(bowlingTable);
    }

    private void addHeaderRow(Table table, PdfFont bold, String[] headers) {
        for (String h : headers) {
            table.addHeaderCell(new Cell().add(new Paragraph(h).setFont(bold).setFontSize(9))
                    .setBackgroundColor(new DeviceRgb(30, 30, 90))
                    .setFontColor(DeviceRgb.WHITE));
        }
    }
}
